services:
  app:
    build: .
    ports:
      - "7860:7860"  # Main application port
      - "80:7860"    # Map port 80 to the application for health checks
    volumes:
      - ./images:/app/images
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge 